export const DEFAULT = 'DEFAULT';
export const UPDATE_LOADING_SPINNER_STATE = 'UPDATE_LOADING_SPINNER_STATE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CHECK_LOGIN = 'CHECK_LOGIN';

export const SHOW_ADVERTICE_MODAL = 'SHOW_ADVERTICE_MODAL';
export const HIDE_ADVERTICE_MODAL = 'HIDE_ADVERTICE_MODAL';
