

export const GET_ALL_STUDENTS_INFO = 'GET_ALL_STUDENTS_INFO';
export const GET_ALL_STUDENTS_INFO_OK = 'GET_ALL_STUDENTS_INFO_OK';

export const GET_ALL_STUDENTS_MARKS_INFO = 'GET_ALL_STUDENTS_MARKS_INFO';
export const GET_ALL_STUDENTS_MARKS_INFO_OK = 'GET_ALL_STUDENTS_MARKS_INFO_OK';