export const GET_BATTLE_NUMS = 'GET_BATTLE_NUMS';
export const GET_BATTLE_NUMS_OK = 'GET_BATTLE_NUMS_OK';

export const GET_USER_BATTLE_MARKS = 'GET_USER_BATTLE_MARKS';
export const GET_USER_BATTLE_MARKS_OK = 'GET_USER_BATTLE_MARKS_OK';
