export const GET_QUECTIONS = 'GET_QUECTIONS';
export const GET_QUECTIONS_OK = 'GET_QUECTIONS_OK';

export const GET_BATTLE_QUECTIONS = 'GET_BATTLE_QUECTIONS';
export const GET_BATTLE_QUECTIONS_OK = 'GET_BATTLE_QUECTIONS_OK';

export const GET_USER_REVIEW = 'GET_USER_REVIEW';
export const GET_USER_REVIEW_OK = 'GET_USER_REVIEW_OK';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_OK = 'ADD_REVIEW_OK';

export const DELETE_REVIEW = 'DELETE_REVIEW';
export const DELETE_REVIEW_OK = 'DELETE_REVIEW_OK';

export const SHOW_ADVERTICE = 'SHOW_ADVERTICE';
export const SHOW_ADVERTICE_OK = 'SHOW_ADVERTICE_OK';

export const ADD_BATTLE_MARKS = 'ADD_BATTLE_MARKS';
export const ADD_BATTLE_MARKS_OK = 'ADD_BATTLE_MARKS_OK';
