export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_OK = 'GET_USER_INFO_OK';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_OK = 'UPDATE_USER_INFO_OK';
